version: '2'

services:
  inventoryapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  locationapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  transportapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
